### ISSUE TITLE
Setup SSH

### ISSUE THREAD

**Issue by TheColorman** [DannyDannyDanny/mulbo#3]
See "[Enabling SSH](https://linuxize.com/post/how-to-enable-ssh-on-ubuntu-18-04/)" and "[Setting up SSH Keys](https://www.digitalocean.com/community/tutorials/how-to-set-up-ssh-keys-on-ubuntu-1804)".

**Comment by DannyDannyDanny** [comment]
Looks super good. I'll wipe the RPI and reinstall linux on it 👍🏻

**Comment by DannyDannyDanny** [comment]
I'll keep this comment updated
* [x] [Ubuntu installation](https://ubuntu.com/download/iot/installation-media#macos)
* [ ] [Enabling SSH](https://linuxize.com/post/how-to-enable-ssh-on-ubuntu-18-04/)
* [ ] [Setting up SSH Keys](https://www.digitalocean.com/community/tutorials/how-to-set-up-ssh-keys-on-ubuntu-1804)".
