### ISSUE TITLE
Design and build front-end for MVP functionality

### ISSUE THREAD

**Issue by DannyDannyDanny** [DannyDannyDanny/mulbo#4]
### Minimum Viable Product
* RPI hosts API endpoint that takes a `POST`-request with a string of max 300 characters
* RPI hosts a front-end that utilizes the API

This solution to this issue should propose a front end first via screenshots / mocks and then with some supplementary code.

**Comment by TheColorman** [comment]
What exactly is the functionality of this specific API? The project description contains seemingly multiple "sub-projects".

**Comment by DannyDannyDanny** [comment]
I suggest we start with something minimal that works. As we expand the scope and refine the project goal(s), we'll update the description.

**The minimum viable product (MVP) is an API that takes an a single string of up to 300 characters and stores it server side.** 

The API back-end can be written in either node or python to start with. Once it is written and runs locally we'll host it on a server and set up continuous integration.

**Comment by TheColorman** [comment]
I've made a quick mockup, is this it?

![image](https://user-images.githubusercontent.com/18369995/113167486-0f79bd00-9244-11eb-8de1-4d1f761d2fe3.png)

**Comment by TheColorman** [comment]
I've written a simple frontend with the ability to POST the input string, where should I upload it?

**Comment by DannyDannyDanny** [comment]
Make a new directory in the rootfolder `frontend-mvp/` and throw all the files and dependencies in there. Add a markdown files with a short explanation on how to launch it 👍🏻

**Comment by DannyDannyDanny** [comment]
I think we've fulfilled the front-end MVP criteria!
